import type { Tool } from '@aitools/shared';

export const MOCK_TOOLS: Tool[] = [
  {
    id: '1',
    slug: 'cline',
    name: 'Cline',
    tagline: 'Open source AI coding agent with frontier models',
    description: 'Cline is an open source AI coding agent that helps you write code faster using frontier models. It integrates directly into your IDE.',
    website: 'https://cline.bot',
    categories: ['code-generation', 'automation'],
    industries: ['development'],
    useCases: ['coding', 'debugging'],
    pricingType: 'free',
    isOpenSource: true,
    hasAffiliate: false,
    status: 'approved',
    createdAt: new Date(),
    updatedAt: new Date(),
    previewImg: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=1000&auto=format&fit=crop', // Code editor placeholder
  },
  {
    id: '2',
    slug: 'novu',
    name: 'Novu',
    tagline: 'The open source notification infrastructure',
    description: 'Novu provides a unified API for all your communication channels (Email, SMS, Push, Chat, In-App).',
    website: 'https://novu.co',
    categories: ['automation', 'development'],
    industries: ['development'],
    useCases: ['notifications'],
    pricingType: 'freemium',
    isOpenSource: true,
    hasAffiliate: false,
    status: 'approved',
    createdAt: new Date(),
    updatedAt: new Date(),
    previewImg: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1000&auto=format&fit=crop', // Notifications placeholder
  },
  {
    id: '3',
    slug: 'midjourney',
    name: 'Midjourney',
    tagline: 'AI image generation tool',
    description: 'Midjourney is an independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species.',
    website: 'https://midjourney.com',
    categories: ['image-generation', 'design'],
    industries: ['design', 'marketing'],
    useCases: ['art', 'branding'],
    pricingType: 'paid',
    isOpenSource: false,
    hasAffiliate: false,
    status: 'approved',
    createdAt: new Date(),
    updatedAt: new Date(),
    previewImg: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?q=80&w=1000&auto=format&fit=crop', // Abstract art placeholder
  },
  {
    id: '4',
    slug: 'chatgpt',
    name: 'ChatGPT',
    tagline: 'AI conversational agent',
    description: 'ChatGPT is a free-to-use AI system. Use it for engaging conversations, gain insights, automate tasks, and witness the future of AI, all in one place.',
    website: 'https://chat.openai.com',
    categories: ['copywriting', 'research', 'code-generation'],
    industries: ['marketing', 'development', 'education'],
    useCases: ['writing', 'coding', 'learning'],
    pricingType: 'freemium',
    isOpenSource: false,
    hasAffiliate: false,
    status: 'approved',
    createdAt: new Date(),
    updatedAt: new Date(),
    previewImg: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1000&auto=format&fit=crop', // AI chat placeholder
  },
  {
    id: '5',
    slug: 'n8n',
    name: 'n8n',
    tagline: 'Fair-code workflow automation tool',
    description: 'n8n is an extendable workflow automation tool. With a fair-code distribution model, it will always have visible source code, be available to self-host, and allow you to add your own custom functions, logic and apps.',
    website: 'https://n8n.io',
    categories: ['automation'],
    industries: ['development', 'marketing'],
    useCases: ['workflow', 'integration'],
    pricingType: 'freemium',
    isOpenSource: true,
    hasAffiliate: false,
    status: 'approved',
    createdAt: new Date(),
    updatedAt: new Date(),
    previewImg: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1000&auto=format&fit=crop', // Workflow/nodes placeholder
  },
  {
    id: '6',
    slug: 'cal-com',
    name: 'Cal.com',
    tagline: 'Scheduling infrastructure for everyone',
    description: 'Cal.com is the open source scheduling infrastructure for everyone. It is a white-label scheduling platform that you can host yourself.',
    website: 'https://cal.com',
    categories: ['productivity'],
    industries: ['sales', 'marketing'],
    useCases: ['scheduling'],
    pricingType: 'freemium',
    isOpenSource: true,
    hasAffiliate: false,
    status: 'approved',
    createdAt: new Date(),
    updatedAt: new Date(),
    previewImg: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?q=80&w=1000&auto=format&fit=crop', // Calendar/schedule placeholder
  },
  {
    id: '7',
    slug: 'obsidian',
    name: 'Obsidian',
    tagline: 'A second brain, for you, forever',
    description: 'Obsidian is a powerful knowledge base on top of a local folder of plain text Markdown files.',
    website: 'https://obsidian.md',
    categories: ['productivity', 'research'],
    industries: ['education', 'research'],
    useCases: ['notes', 'writing'],
    pricingType: 'free',
    isOpenSource: false,
    hasAffiliate: false,
    status: 'approved',
    createdAt: new Date(),
    updatedAt: new Date(),
    previewImg: 'https://images.unsplash.com/photo-1456324504439-367cee13d656?q=80&w=1000&auto=format&fit=crop', // Notes placeholder
  },
  {
    id: '8',
    slug: 'supabase',
    name: 'Supabase',
    tagline: 'The Open Source Firebase Alternative',
    description: 'Supabase is an open source Firebase alternative. Start your project with a Postgres database, Authentication, instant APIs, Edge Functions, Realtime subscriptions, and Storage.',
    website: 'https://supabase.com',
    categories: ['development'],
    industries: ['development'],
    useCases: ['backend', 'database'],
    pricingType: 'freemium',
    isOpenSource: true,
    hasAffiliate: false,
    status: 'approved',
    createdAt: new Date(),
    updatedAt: new Date(),
    previewImg: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?q=80&w=1000&auto=format&fit=crop', // Database/server placeholder
  },
];
